/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Database: typeof import('./src/components/database.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LoginCard: typeof import('./src/components/userManagement/LoginCard.vue')['default']
    NewAccountCard: typeof import('./src/components/userManagement/NewAccountCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
